[tool.black]
line-length = 128
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 128
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 128
target-version = "py311"
select = ["E", "F", "I"]  # E: pycodestyle, F: pyflakes, I: isort rules
ignore = []

[tool.ruff.format]
quote-style = "double"